first commit for Force Control documentation
icub-tech-iit/documentation pull request #201
Opened 2022-03-08 15:28 UTC by davidetome

This PR aims to start a discussion on what material have to be migrated/updated.

cc @pattacini @traversaro

2022-03-10 14:31 UTC, pattacini requested changes
## MoM of the meeting held between @davidetome @traversaro and @pattacini

We decided to proceed in 2 steps.

### Step 1
- Migrate the wiki page http://wiki.icub.org/wiki/Force_Control first.
- Remove the table as it is deprecated now.
- Keep the description of the control modes as they're quite useful although we will very likely move them to a different page in the near future.
- Replace all the old machinery with the latest one.

### Step 2
- Deal with the device-based WBD.

2022-03-15 10:26 UTC, davidetome commented
As [agreed](https://github.com/icub-tech-iit/documentation/pull/201#pullrequestreview-905921252) , I made some mods

2022-03-15 11:14 UTC, pattacini reviewed
Just a few initial comments @davidetome.

I've proposed commits to fix some section titles where colors show up. The index gets messed up indeed:

<img width="123" alt="image" src="https://user-images.githubusercontent.com/3738070/158365380-23707df9-056a-4632-88f4-76a0b9513971.png">

I'd highlight the port names using this `markdown formatting`.

Did you also make sure to delete images that are no longer used?

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Position control mode <font color="#95ddba">███</font></li></ul>
```suggestion
#### Position control mode
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Velocity control mode <font color="#96beff">███</font></li></ul>
```suggestion
#### Velocity control mode
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Torque control mode <font color="#ff6464">███</font></li></ul>
```suggestion
#### Torque control mode
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Openloop control mode <font color="#000000">░░░</font></li></ul>
```suggestion
#### Openloop control mode
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Impedance Position control mode <font color="#dcbedc">███</font></li></ul>
```suggestion
#### Impedance Position control mode
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Impedance Velocity control mode <font color="#dcbedc">███</font></li></ul>
```suggestion
#### Impedance Velocity control mode
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +#### Idle <font color="#f9ec8d">███</font></li></ul>
```suggestion
#### Idle
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +wholeBodyDynamics and `yarprobotinterface`` communicate through yarp ports:
```suggestion
wholeBodyDynamics and `yarprobotinterface` communicate through yarp ports:
```

2022-03-15 11:14 UTC, pattacini commented on docs/icub_force_control/icub-force-control.md
> +/icub/inertial provides 3DOF orientation tracker measurements
```suggestion
`/icub/inertial` provides 3DOF orientation tracker measurements
```
I would enclose all port names within grave accents in order to improve the formatting.

2022-03-15 12:21 UTC, pattacini requested changes
Hi @davidetome 

I can see only 3 images of the `yarpmanager` rendered: one seems to be missing.

Also, all the images should be rendered approximately with the same size but this is not the case.

2022-03-15 12:40 UTC, davidetome commented
should be fixed 👍🏻

2022-03-15 12:44 UTC, pattacini approved these changes
Nicely done @davidetome 👍🏻 
I deem we're done with step 1.
What do you think @traversaro ?

2022-03-24 10:03 UTC, davidetome commented
Ciao @pattacini , about Step 2,  I already ported [this page](https://github.com/robotology/whole-body-estimators/blob/master/doc/howto/force_control_on_icub.md) on the top of the document, do you think something else is missing? @traversaro what do you think?

2022-03-24 10:47 UTC, pattacini commented
>on the top of the document

On the top is not the correct place. We said that the classical module-based WBD is still the official one, hence it has to receive the focus.

Let's put it at the bottom then.

2022-03-24 10:50 UTC, davidetome commented
> > on the top of the document
> 
> The top is not the correct place. We said that the classical module-based WBD is still the official one, hence it has to receive the focus.
> 
> Let's put the service-based WBD at the bottom then.

I thought the same, I agree 👍🏻

2022-03-24 11:02 UTC, traversaro commented
I agree!

2022-03-25 10:02 UTC, davidetome commented
@pattacini @traversaro , I did the mods and added some missing parts..

2022-03-25 10:45 UTC, pattacini commented
The failure in the CI is not related to the content of this PR.
cc @davidetome

2022-03-28 08:55 UTC, pattacini commented
> The failure in the CI is not related to the content of this PR. cc @davidetome

The GA framework is operational again. I'll merge the PR then.

2022-03-28 08:55 UTC, merged