[Robot Testing]: Added dedicated category, iCubTest app instructions and proto wiki migration
icub-tech-iit/documentation pull request #224
Opened 2022-09-16 13:44 UTC by gsisinna

As per the title, the following PR intends to integrate in the official documentation all those pages and references useful to perform testing on iCub, starting from production tests for encoders and joint limits as well as higher level functional tests like the redball demo.

In particular with https://github.com/icub-tech-iit/documentation/commit/12f423e0dacee817930aa8ce9b94893a0933c4bb has been clarified more about the procedure for starting the new iCubTest application developed for automated, docker deployment-based testing.

2022-09-17 09:33 UTC, pattacini requested changes
Hi @gsisinna 
Thanks for your nice contribution!

## Duplicates
I've spotted some repetitions I would honestly avoid.

The following topics are already contained in the [iCub First Steps](https://icub-tech-iit.github.io/documentation/icub_starter_kits/first_steps/):
- Face Expressions
- Red Ball (Manual)
- Skin

I'd like to stick to the starter kit; therefore, you may consider integrating therein any further note and/or text you came up with.
Then, remember to clean up the PR removing unnecessary images.

## Images
Also, please, center the images using the syntax below:

```markdown
<center>
<img src ="../img/Picture1.png"/>
</center>
```

## TOC
Somehow, your rendered pages do not show the Table-Of-Contents section on the top-right corner.
I can look into it once the PR is merged.

2022-09-17 09:33 UTC, pattacini commented on docs/icub_testing/icubtest_application.md
> +**IMPORTANT: For any emergency or safety STOP, always keep the FAULT button handy and press it to switch off power to the motors.**
You may use [MkDocs Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) here. I think the `warning` type is appropriate.

2022-09-23 09:24 UTC, gsisinna commented on docs/icub_testing/icubtest_application.md
> +**IMPORTANT: For any emergency or safety STOP, always keep the FAULT button handy and press it to switch off power to the motors.**
Done!

2022-09-23 11:27 UTC, pattacini requested changes
Fantastic, thanks @gsisinna 👍🏻 

Could you only please remove the image `versions.PNG`, which doesn't seem to be used?

2022-09-23 11:42 UTC, pattacini approved these changes

2022-09-23 11:42 UTC, merged