Added robot configuration documentation
icub-tech-iit/documentation pull request #234
Opened 2022-11-29 10:25 UTC by valegagge

In this PR I added all info about the robots-configuration available on the [icub-wiki](http://wiki-icub.iit.local/index.php/Main_Page).

2022-11-29 10:39 UTC, pattacini commented
Thanks heaps for the contribution @valegagge 👍🏻 
I'll review the PR asap.

2022-11-29 12:39 UTC, pattacini requested changes
Well done 👍🏻 
Just a few additions you may accept straight away from the PR dashboard.

2022-11-29 12:39 UTC, pattacini commented on docs/icub_robot_configuration/naming_convention/naming_convention.md
> + ```
```suggestion
 ```xml
```

This serves to better render the code snippet.

2022-11-29 12:39 UTC, pattacini commented on docs/icub_robot_configuration/structure_robot_configuration_data_set/structure_robot_configuration_data_set.md
> +```
```suggestion
```xml
```

This serves to better render the code snippet.

2022-11-29 12:39 UTC, pattacini commented on docs/icub_robot_configuration/icub_robot_configuration_index.md
> +This mean that in the newest version may be available new parameters or there are some changes that are not described in the last stable version. You can find these difference in the changelog.
```suggestion
## Note for robots hosted at the iCub Tech Facility
Robots hosted at the iCub Tech Facility often run developing software, that is, they use the same software modules, but on the development branch instead of stable (master).
This means that in the newest version new parameters may be available or there might be some changes that are not described in the latest stable version. You can find these differences in the changelog.
```

2022-11-29 12:39 UTC, pattacini commented on docs/icub_robot_configuration/icub_robot_configuration_index.md
> +If you are interesting in the meaning of this changes, please check iCubTemplates/iCubTemplateVX_0, where X is the last version in the devel branch.
```suggestion
If you are interested in the rationale underlying these changes, please check the files `[iCubTemplates](https://github.com/robotology/robots-configuration/tree/devel/iCubTemplates)/iCubTemplateVX_0`, where `X` identifies the latest version in the devel branch.
```

2022-11-30 09:23 UTC, valegagge commented
> Just a few additions you may accept straight away from the PR dashboard by clicking on the commit suggestion.

thanks!!!

2022-11-30 09:41 UTC, pattacini approved these changes

2022-11-30 09:42 UTC, merged