Updating UKIT 008
icub-tech-iit/documentation pull request #270
Opened 2023-05-09 09:40 UTC by Mick3Lozzo

Updating UKIT 008 instructions with the inclusion of RealSense D405 and its related cable.

2023-05-09 10:01 UTC, pattacini requested changes

2023-05-09 10:01 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +| <img src="img\11.PNG" height=250 > | <img src="img\8.PNG" height=250 > | <img src="img\9.PNG" height=250 > |
We need forward slashes here.

2023-05-09 10:01 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> + <img src="img/2.PNG" height=400 alignement=center >
Did you check that the alignment specified this way actually works?

2023-05-09 10:01 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> + **NOTE:** As mentioned above, the RealSense D405 uses a different cable too.
Same comment as above.

2023-05-10 08:40 UTC, Mick3Lozzo commented on docs/upgrade_kits/realsense_holder/support.md
> +| <img src="img\11.PNG" height=250 > | <img src="img\8.PNG" height=250 > | <img src="img\9.PNG" height=250 > |
Corrected @pattacini

2023-05-10 12:08 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +> [Logic schematics](https://github.com/icub-tech-iit/electronics-wiring-public/tree/master/icub-upgrade-kits/kit_008/15389%20-%20iCub2.5%20Head%20RealSense%20upgrade%20kit%20(electronic%20parts))
Wrong

2023-05-10 12:08 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +> See [Harness schematics](https://github.com/icub-tech-iit/electronics-wiring-public/tree/master/icub-upgrade-kits/kit_008/15393%20-%20iCub2.5%20Head%20RealSense%20upgrade%20kit%20(wiring%20parts))
Wrong

2023-05-10 12:08 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +> <img src="img/6.PNG" height=400 alignement=center >
Wrong

2023-05-10 12:31 UTC, Mick3Lozzo commented on docs/upgrade_kits/realsense_holder/support.md
> + <img src="img/2.PNG" height=400 alignement=center >
I tried something other but didn't work. For now, I'm not centring the pictures anymore.

2023-05-10 12:35 UTC, Mick3Lozzo commented on docs/upgrade_kits/realsense_holder/support.md
> +**NOTE**: The following instructions are provided for assembling the D435i model of RealSense camera.
The title is out of the admonition box. What I am doing wrong @pattacini? I'm following this format:  
  
!!! note "Phasellus posuere in sem ut cursus" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.

2023-05-10 12:40 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> + <img src="img/2.PNG" height=400 alignement=center >
We need to center images. So, please stick to the previous format that was relying on `<center>...</center>`.

2023-05-10 12:42 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +**NOTE**: The following instructions are provided for assembling the D435i model of RealSense camera.
Before it wasn't correct. I've seen you fixed it in the latest commits.

2023-05-10 12:52 UTC, Mick3Lozzo commented on docs/upgrade_kits/realsense_holder/support.md
> + <img src="img/2.PNG" height=400 alignement=center >
Re-centered pictures @pattacini

2023-05-10 12:54 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +<img src="img/5.PNG" height=500>
```suggestion
<center> <img src="img/5.PNG" height=500> </center>
```

2023-05-10 12:54 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +The holder has bee to be compatible with the following RealSense models:
```suggestion
The holder has been designed to be compatible with the following RealSense models:
```

2023-05-10 12:55 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
> +<img src="img/5.PNG" height=500>
You could commit the suggestion straight away @Mick3Lozzo.

2023-05-10 13:04 UTC, pattacini approved these changes
Fine with me so far from a rendering standpoint, @Miche19 👍🏻 
At any rate, we should wait for high-level reviews on the content.

2023-05-15 10:35 UTC, pattacini requested changes
Hi @Mick3Lozzo 

Could you please replace the files archived in this zip?
[amends.zip](https://github.com/icub-tech-iit/documentation/files/11476844/amends.zip)

The images are such that they're shown equally well in the first table. 
Also, please, remove the unused file `7.PNG`.

2023-05-15 15:35 UTC, pattacini commented on docs/upgrade_kits/realsense_holder/support.md
>  |    IIT alias (used as ordering reference)| KIT_008  |
```suggestion
|  |  |  |
| :---: | :---: | :---: |
| <img src="../img/11.PNG"> | <img src="../img/8.PNG"> | <img src="../img/9.PNG"> |

|  |  |
| :--- | :--- |
|  IIT alias (used as ordering reference) | KIT_008  |
```

2023-05-17 09:08 UTC, pattacini approved these changes

2023-05-17 09:08 UTC, merged