Wrist Mk2.1 info integration
icub-tech-iit/documentation pull request #283
Opened 2023-06-14 07:03 UTC by Lawproto

Adding some info regarding our latest designed wrist, also moving some bits from the hand section to the wrist.

2023-06-14 08:18 UTC, Lawproto commented on docs/wrists/wrist_mk2.md
> +  <img  src=    "./img/mk2.0_vs_mk2.1.png"
```suggestion
  <img  src=    "../img/mk2.0_vs_mk2.1.png"
```

2023-06-14 08:18 UTC, Lawproto commented on docs/wrists/wrist_mk2.md
> +  <img  src=    "./img/pitches.png"
```suggestion
  <img  src=    "../img/pitches.png"
```

2023-06-14 08:19 UTC, Lawproto commented on docs/wrists/wrist_mk2.md
> +  <img  src=    "./img/wrist-yaw-roll.png"
```suggestion
  <img  src=    "../img/wrist-yaw-roll.png"
```

2023-06-14 09:15 UTC, pattacini requested changes
Hi @Lawproto 

Thanks for the fixes!

We also need to fix/update the following in the main navigation section:

https://github.com/Lawproto/documentation/blob/wrist_patch/mkdocs.yml#L169-L170

2023-06-14 09:15 UTC, pattacini commented on docs/wrists/wrist_mk2_math.md
> +- The above numbers are referred to the **left** employment of the wrist mechanism. In order to use it in the **right** configuration, an offset of $180^\circ$ must be added so that the whole mechani
>Thus, at rest, the arm angles will be $\theta_1=270^\circ$, $\theta_2=30^\circ$ and $\theta_3=150^\circ$. This implies that the rest position must be set by properly calibrating the arm position sensors on the software side, while the hand interface must be rotated by $180^\circ$ with respect to the platform on the hardware side.

Is this still valid for Mk2.1?

If not, I would update this section to be compatible with the latest version only.

2023-06-14 09:57 UTC, Lawproto commented on docs/wrists/wrist_mk2_math.md
> +- The above numbers are referred to the **left** employment of the wrist mechanism. In order to use it in the **right** configuration, an offset of $180^\circ$ must be added so that the whole mechani
good point! I think not, but I have to read more in depth and understand what those angles refer to.

2023-06-16 09:41 UTC, pattacini commented
Thanks heaps @Lawproto for the updates!

The last point to address is:

>We also need to fix/update the following in the main navigation section:
>
>https://github.com/Lawproto/documentation/blob/wrist_patch/mkdocs.yml#L169-L170

2023-06-16 09:41 UTC, Lawproto commented on docs/wrists/wrist_mk2_math.md
> +- The above numbers are referred to the **left** employment of the wrist mechanism. In order to use it in the **right** configuration, an offset of $180^\circ$ must be added so that the whole mechani
@pattacini I corrected the angles to the current situation. Fun fact: Mk2.0 was not symmetrical as the text stated but Mk2.1 is instead and made it all work again.

2023-06-16 09:55 UTC, Lawproto commented
> Thanks heaps @Lawproto for the updates!
> 
> The last point to address is:
> 
> > We also need to fix/update the following in the main navigation section:
> > https://github.com/Lawproto/documentation/blob/wrist_patch/mkdocs.yml#L169-L170

@pattacini done.

2023-06-16 09:57 UTC, pattacini approved these changes

2023-06-16 09:57 UTC, merged