First draft of available sensors' documentation
icub-tech-iit/documentation pull request #286
Opened 2023-06-26 10:12 UTC by mfussi66

This PR begins addressing https://github.com/icub-tech-iit/documentation/issues/271, by taking inspiration from the OP. 
The idea is to have a dedicated page where each type of sensor (controlboard included) has their own server and client briefly described, with links to the YARP docs. Then, for each, robot, a list of the mounted sensors and basic info on how to access their data.

2023-06-26 10:16 UTC, pattacini commented on docs/icub_sensors/icub27_sensors.md
Or even `icub2.7_`

2023-06-26 10:19 UTC, mfussi66 commented on docs/icub_sensors/icub27_sensors.md
I guess `icub2.7_` could be good! 2x_ might be too general.

2023-06-26 13:33 UTC, pattacini requested changes
Better off using mkdocs admonitions.
See inline comments.

2023-06-26 13:33 UTC, pattacini commented on docs/icub_sensors/yarp_nws_convention.md
> +
Use [mkdocs admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage) instead

2023-06-26 13:34 UTC, pattacini commented on docs/icub_sensors/yarp_nws_convention.md
> +**Note: At the moment no client device is available for depth cameras, so the server needs to be accessed directly from the above ports.**
Use [mkdocs admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage) instead

2023-06-26 20:17 UTC, pattacini requested changes
One last comment to address from my side before merging this iteration.

2023-06-26 20:17 UTC, pattacini commented on mkdocs.yml
> +      - Sensor interfaces: icub_sensors/index.md
Nitpicking, but we could replicate here the hierarchy with sublevels, as done with the other resources.

2023-06-27 06:51 UTC, pattacini requested changes
Since we deal with a variety of robots here, why don't we change references to `icub_sensors` into `robot_sensors`? This is just to remain a little bit more generic.

2023-06-27 10:48 UTC, mfussi66 commented on mkdocs.yml
> +      - Sensor interfaces: icub_sensors/index.md
Done!

2023-06-27 11:16 UTC, pattacini approved these changes

2023-06-27 11:17 UTC, merged