Update documentation calib14
icub-tech-iit/documentation pull request #293
Opened 2023-07-25 11:52 UTC by MSECode

Update calibration14 documentation with procedure to follow for finding correct values of calibration parameters to be set in the configuration files

2023-07-25 12:07 UTC, pattacini requested changes
Some text steamline.
@MSECode, please double-check.

2023-07-25 12:07 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +First of all, the user should set the boolean values `skipCalibration` and `useRawEncoderData` in the file `general.xml` to `true`, therefore the calibration procedure won't start at `yarprobotinterf
```suggestion
First, set to `true` the boolean variables `skipCalibration` and `useRawEncoderData` in the file `general.xml`. This is meant to disable calibration at `yarprobotinterface` startup. Also, this will make the port `/ergocub/left_arm/state:o` print the raw values (i.e., uncalibrated) for the finger joint encoders. 
```

2023-07-25 12:07 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +Done that, the user should check the values printed out by the port running in a terminal the command:
```suggestion
Once done, you should check the values printed out by the port running in a terminal the command:
```

2023-07-25 12:07 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +and by doing this observing which should be the raw value of the offset for the encoder joint when the finger is at the hard-stop position (ideally finger full open). Thus, the user should set this v
```suggestion
While doing so, pay attention to the raw value of the offset of the encoder joint when the finger is at the hard-stop position (ideally, the finger is fully open). This is the value (with the opposite sign) to be set for the parameter `calibration5`.
```

2023-07-25 12:07 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +After that, by observing how the values printed out by the port change, the user would check if the `invert direction`, i.e. `calibration3` value, should be `1` or `0` and if a specific value of rota
```suggestion
After that, while observing how the printed values change, you can check if the `invert direction` (i.e., the `calibration3` value), shall be `1` or `0`, and if a specific value of rotation shall be added up to `calibration4` to prevent the encoder from crossing the zero while finger joint is moving.
```

2023-07-25 12:34 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +
Better off going with:

\```console
yarp read ... /ergocub/left_arm/state:o 
\```

2023-07-26 07:26 UTC, pattacini approved these changes

2023-07-26 09:15 UTC, pattacini requested changes
I've still noticed something to streamline to improve reading.

2023-07-26 09:15 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +```
We need a blank line hereinafter.

2023-07-26 09:15 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +After that, by observing how the values printed out by the port change, the user would check if the `invert direction`, i.e. `calibration3` value, should be `1` or `0` and if a specific value of rota
Hi @MSECode 

Would you mind harmonizing the text by, for example, replacing `user` with `you`?

2023-07-26 09:17 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +After that, by observing how the values printed out by the port change, the user would check if the `invert direction`, i.e. `calibration3` value, should be `1` or `0` and if a specific value of rota
Also,

```
avoid the encder to cross the zero while finger joint is moving.
```

should be

```
prevent the encoder from crossing the zero while finger joint is moving.
```

2023-07-26 09:32 UTC, MSECode commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +```
oks I'll fix that

2023-07-26 09:36 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +and by doing this observing which should be the raw value of the offset for the encoder joint when the finger is at the hard-stop position (ideally finger full open). Thus, you should set this value
```
and by doing this observing which should be the raw value of the offset for the encoder joint when the finger is at the hard-stop position (ideally finger full open).
```

This part doesn't read well. Could you rephrase it?

2023-07-26 09:44 UTC, MSECode commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +and by doing this observing which should be the raw value of the offset for the encoder joint when the finger is at the hard-stop position (ideally finger full open). Thus, you should set this value
sure thing

2023-07-26 09:49 UTC, pattacini approved these changes

2023-07-26 09:50 UTC, pattacini commented on docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
> +and by doing this observing which should be the raw value of the offset for the encoder joint when the finger is at the hard-stop position (ideally finger full open). Thus, you should set this value
Thanks!

2023-07-26 09:51 UTC, pattacini commented
@MSECode 

I think the PR is mergeable now.
The PR is still in draft. Do you want me to wait for the FW PR's to be merged first?

2023-07-28 08:01 UTC, pattacini approved these changes

2023-07-28 08:01 UTC, merged