First attempt to add ergocub sw documentation
icub-tech-iit/documentation pull request #318
Opened 2023-09-20 08:47 UTC by martinaxgloria

Since #282, I'd like to add a new section within `icub-tech documentation` that would be specific for ergocub software (like for icub hw and icub sw). My idea is to document the installation of both `ergocub-head` and `ergocub-torso` and the specific procedures and modules for each of them (e.g. librealsense installation for ergocub-head), the ergocub network specs (made by @davidelasagna) and other stuff that are not completely linked to icub documentation.

In this PR, I proposed a potential new layout with some sections already filled in thanks to @davidelasagna.

cc @Nicogene @pattacini @traversaro

2023-09-20 11:14 UTC, pattacini requested changes
Hi @martinaxgloria 

Thanks for the nice addition 👍🏻 

I would avoid creating a dedicated overall section to ergoCub at that major level.

There is already lots of stuff dedicated to this new robot that lies within the HW and SW sections, which are meant to comprise everything, although they contain the keyword `iCub`.

So, my suggestion is to go with dedicated ergoCub pages that need to be created in the section related to the installation.

2023-09-20 11:14 UTC, pattacini commented on docs/index.md
> +#### [:computer:{.blink} Documentation resources on the `ergoCub Software`](ergocub_sw.md)
To be removed.

2023-09-20 11:14 UTC, pattacini commented on mkdocs.yml
> +          - Install from scratch: ergocub_operating_systems/ergocub_torso/install_from_scratch.md
To be refactored.

2023-09-20 11:56 UTC, martinaxgloria commented
Hi @pattacini,

I got the point. I'll remove the major section I've created and I'll move the pages under the iCub software section

2023-09-20 14:59 UTC, martinaxgloria commented
Hi @pattacini, 

As you proposed, I made some changes here https://github.com/icub-tech-iit/documentation/pull/318/commits/009b1e630e0462c2385465dcc5a757aa16624222

2023-10-26 12:02 UTC, martinaxgloria commented
With https://github.com/icub-tech-iit/documentation/pull/318/commits/b6f060ee5e369c134c80ef259ccf7a4be4f8f265, I added other pieces of documentation and the references to the existing pages with the specs for ergocub. 

cc @Nicogene @pattacini @traversaro

2023-10-26 12:13 UTC, traversaro commented
Thanks! 

fyi @S-Dafarra @GiulioRomualdi

2023-10-27 09:03 UTC, Nicogene approved these changes
Reviewed irl, LGTM!

2023-10-27 09:39 UTC, Nicogene commented
@traversaro if it is ok for you we could merge it

2023-10-27 09:49 UTC, pattacini commented
> @traversaro if it is ok for you we could merge it

I'll also give it a second pass of review.

2023-10-27 11:59 UTC, traversaro approved these changes

2023-10-27 12:11 UTC, mebbaid commented on docs/ergocub_operating_systems/ergocub_torso/install_from_scratch.md
> +
minor typo in " ...  and then we manually ..."

2023-10-27 12:14 UTC, martinaxgloria commented on docs/ergocub_operating_systems/ergocub_torso/install_from_scratch.md
> +
Done https://github.com/icub-tech-iit/documentation/pull/318/commits/9cbddabddfdb64e7bb7705f85162cc9da1869dcd. Thanks!

2023-10-27 12:47 UTC, mebbaid commented on docs/ergocub_operating_systems/network.md
> +
above is true originally. Not sure if some change to `10.0.2.4` was done on ergocub laptop side recently? perhaps @davidelasagna / @S-Dafarra can attest ?

2023-10-27 13:13 UTC, S-Dafarra commented on docs/ergocub_operating_systems/network.md
> +
Nope, those info are still ok. The laptop is just another node whose address is relevant only for the YARP network

2023-10-27 13:26 UTC, mebbaid approved these changes

2023-10-27 14:39 UTC, pattacini requested changes
Hi @martinaxgloria 

There are conflicting files needing your care.

2023-10-27 14:55 UTC, pattacini requested changes
Some other quick suggested inline amendments.

2023-10-27 14:55 UTC, pattacini commented on docs/ergocub_operating_systems/ergocub_torso/install_from_scratch.md
> +!!!note
```suggestion
!!! note
```

Probably working also before, but the official doc reports that we need a space.
See https://squidfunk.github.io/mkdocs-material/reference/admonitions/

2023-10-27 14:55 UTC, pattacini commented on docs/ergocub_operating_systems/ergocub_torso/install_from_scratch.md
> +To install the OS from scratch, please follow [this guide](../../icub_operating_systems/icubos/installation-from-scratch.md), being carefull to install the [**Ubuntu 22.04 LTS Server**](https://relea
```suggestion
To install the OS from scratch, please follow [this guide](../../icub_operating_systems/icubos/installation-from-scratch.md), being careful to install the [**Ubuntu 22.04 LTS Server**](https://releases.ubuntu.com/focal).
```

2023-10-27 14:55 UTC, pattacini commented on docs/ergocub_operating_systems/network.md
> +This configuration depends deeply from the motor control board firmware and thus it can't be changed.
```suggestion
This configuration depends deeply on the motor control board firmware and thus it can't be changed.
```

2023-10-27 14:55 UTC, pattacini commented on docs/ergocub_operating_systems/network.md
> +since this is a segregated network, there is no default gateway.
```suggestion
Since this is a segregated network, there is no default gateway.
```

2023-10-27 14:55 UTC, pattacini commented on docs/icub_operating_systems/icubos/jetpack.md
> +This guide is intended for a developer that wants to flash and setup the [Nvidia Jetson Xavier boards](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-xavier-series/) (i.e. A
```suggestion
This guide is intended for developers who want to flash and set up the [Nvidia Jetson Xavier boards](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-xavier-series/) (i.e., AXG, NX).
```

2023-10-27 14:59 UTC, pattacini commented
> Hi @martinaxgloria
> 
> There are conflicting files needing your care.

I did it myself.

2023-10-27 15:01 UTC, pattacini commented
> Some other quick suggested inline amendments.

Done!

2023-10-27 15:01 UTC, merged

2023-10-27 19:11 UTC, martinaxgloria commented
Thank you so much @pattacini!