Update the iCub user enviroment documentation
icub-tech-iit/documentation pull request #325
Opened 2023-10-31 19:59 UTC by GiulioRomualdi

This closes https://github.com/icub-tech-iit/documentation/issues/324

2023-10-31 21:04 UTC, pattacini requested changes
Thank you @GiulioRomualdi!
For consistency, would you mind updating also the following snippet https://github.com/icub-tech-iit/documentation/blob/5d919960f2d71e25d845b1eb4b899ed0c389ae43/docs/icub_operating_systems/pc104/the-icub-live-details.md?plain=1#L302-L351

as reported in https://github.com/icub-tech-iit/documentation/issues/324#issuecomment-1787248578?

2023-11-02 17:23 UTC, GiulioRomualdi commented
Hi @pattacini I updated the file in https://github.com/icub-tech-iit/documentation/pull/325/commits/3323f66a3b0e179d2374d09644c258ada9314b33

2023-11-03 06:38 UTC, pattacini approved these changes
Super! Thanks.

2023-11-03 06:38 UTC, merged

2023-11-03 13:44 UTC, lrapetti commented on docs/icub_operating_systems/icubos/user-env.md
> +      ICUBRC_FILE="${HOME}/.bashrc_ergoCub"
This was changed from `.bashrc_iCub` to `.bashrc_erogCub`, probably you missed it @pattacini @GiulioRomualdi. 

btw is there an equivalent documentation for ergoCub right?

2023-11-03 14:17 UTC, pattacini commented on docs/icub_operating_systems/icubos/user-env.md
> +      ICUBRC_FILE="${HOME}/.bashrc_ergoCub"
Thanks for pointing that out! I'll revert these changes.

>btw is there an equivalent documentation for ergoCub right?

We have the following doc, which doesn't go into the same level of details:
- https://icub-tech-iit.github.io/documentation/ergocub_operating_systems/

2023-11-03 14:25 UTC, pattacini commented on docs/icub_operating_systems/icubos/user-env.md
> +      ICUBRC_FILE="${HOME}/.bashrc_ergoCub"
Fixed via https://github.com/icub-tech-iit/documentation/commit/e8b2f556e5cdbc7ac4b854dea81161433b93b3c8.