Update BAT and BMS pages
icub-tech-iit/documentation pull request #344
Opened 2024-03-25 15:00 UTC by MSECode

Update info regarding the BAT protocol after addition of new values of current and input voltage and update of timing definition in the documentation 
Add specific page for BMS with info and messages send by BMS and with images for connections to ems
Refactor pages structure for all battery related board

2024-03-25 20:37 UTC, valegagge approved these changes
LGTM

2024-03-25 21:22 UTC, pattacini reviewed
Thank you @MSECode.
I'll review the PR in the next few days.

2024-03-26 08:25 UTC, MSECode commented
> Thank you @MSECode. I'll review the PR in the next few days.

Thanks @pattacini

2024-03-26 15:03 UTC, pattacini requested changes
Hi @MSECode 

I've provided several refinements to improve readability plus some inline comments that require your attention (which I tried to highlight using alerts).

2024-03-26 15:30 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +The data transmitted are related to the system, so to the robot. While the data transmitted by BMS are specifically related to the battery-pack.
The data mentioned in the bullet list in the section `./bat_board/bat_board.md#output-data` are related to the robot (i.e. the system ). This is related to the fact that with the latest changes we have done we realized that BAT and BMS actually send slightly different data even if using the same message. Meaning that BMS can send info only related to the battery pack. Instead the BAT sends info that identify the status of the robot considering that can send data when the robot is powered with the power supply or with the battery. Specifically for BAT:
- Voltage can be either the battery voltage or the power supply voltage
- Current is not the instantaneous current coming out of the batteries but the total current absorbed by the robot
- and so on
So, I've tried to highlight this point specifying that the info shown on the yarp port related to the bat identifies the robot as our system. If we can find a better way to express it, it's more than fine.

2024-03-26 15:31 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +- **Total Current absorbed by the system** (considered as the robot). This is the total current consumption of the system (the sum of the three currents: 42V HSM (power-supply/battery-pack) + 12V mot
yes, the datum displayed on the yarp port and thus meaning to the user is in Ampere

2024-03-26 15:36 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +- **Empty field (NaN)**. This field should be the **average temperature** of the battery pack but this value is not available for the `BAT` board. Since we are currently using the same device for par
raw value is zero. On sw side I'll set it to NaN if equal to zero since 0 could be a temperature value even if likely unreachable. What do u think @valegagge. Should we keep it to zero even of the sw side?

2024-03-26 15:38 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +- Always NaN (Ready for **Average Temperature** of the Battery Pack in $^\circ C$ if available)
Oks, as mentioned before, we set it to NaN on icub-main. I can add a `!!!note` section on the documentation to highlight this point so everyone is aware of this

2024-03-26 15:41 UTC, MSECode commented on docs/battery_boards/bms_board/bms_board.md
> +    Specifically to this message we are sending only the `general alarm status` of the battery pack, stored at `byte 0`. This identifies the single or multiple causes that have sent the `BMS` to an a
clears out maybe is better

2024-03-26 15:47 UTC, pattacini commented on docs/battery_boards/bms_board/bms_board.md
> +    Specifically to this message we are sending only the `general alarm status` of the battery pack, stored at `byte 0`. This identifies the single or multiple causes that have sent the `BMS` to an a
"even if the alarm is cleared".

2024-03-26 15:49 UTC, pattacini commented on docs/battery_boards/bat_board/bat_board.md
> +- Always NaN (Ready for **Average Temperature** of the Battery Pack in $^\circ C$ if available)
Yes an admonition could help in this respect 👍🏻 

`!!!warning` looks better though

2024-03-26 15:53 UTC, pattacini commented on docs/battery_boards/bat_board/bat_board.md
> +The data transmitted are related to the system, so to the robot. While the data transmitted by BMS are specifically related to the battery-pack.
Ok, clear 👍🏻 
So, I would make it like this:
```
The data transmitted by the `BAT` board is related to the overall system, whether the robot is on battery or plugged to the external voltage supply. By contrast, the data transmitted by `BMS` board is specifically related to the battery pack.
```

2024-03-26 15:53 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +- Always NaN (Ready for **Average Temperature** of the Battery Pack in $^\circ C$ if available)
I'll add it then

2024-03-26 16:06 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +The data transmitted are related to the system, so to the robot. While the data transmitted by BMS are specifically related to the battery-pack.
let me add it then

2024-03-26 16:08 UTC, pattacini commented on docs/battery_boards/bat_board/bat_board.md
> +    The **Average Temperature** field is always shown as `NaN` in the `yarp` port related to the `BAT` data. Differently from the `BMS` board, the `BAT` board cannot provide this piece of information
Just for clearness, if I "yarp read" the port, I can see that `NaN` is somehow printed out?

2024-03-26 18:22 UTC, MSECode commented on docs/battery_boards/bat_board/bat_board.md
> +    The **Average Temperature** field is always shown as `NaN` in the `yarp` port related to the `BAT` data. Differently from the `BMS` board, the `BAT` board cannot provide this piece of information
yes , you see nan as in here: https://github.com/robotology/icub-firmware/issues/476#issuecomment-2012347997

2024-03-26 21:12 UTC, pattacini approved these changes

2024-03-26 21:12 UTC, merged