Add new page Calibration type 10 details
icub-tech-iit/documentation pull request #354
Opened 2024-06-20 13:35 UTC by MSECode

Update calibration type 10 doc
Add state machine for showing pipeline of hard-stop calibration when using AMO encoder at joint plus quadrature encoder at motor Add some line detailing the steps of the state machine

This PR aims at adding new details to the calibration type 10, which is the calibration of a joint to a defined hard-stop position, for joints provided with an AMO encoder at the joint and a quadrature encoder at the motor.
Basically a state machine diagram showing the calibration pipeline is shown and described so that now it is easier for somebody to know what is a joint that implements that calibration is doing.

2024-06-20 16:15 UTC, pattacini requested changes
Hi @MSECode 

Thanks for the new page!
Some inline comments to address.

2024-06-20 16:15 UTC, pattacini commented on mkdocs.yml
> +        - AMO Encoder joint calibration type 10 details: robot_calibration_types/amo-encoder-joint-calibration-10-details.md
Adjust the name of the file using underscores.

2024-06-20 16:15 UTC, pattacini commented on docs/robot_calibration_types/standard_calibration_types.md
> +Further details to how the workflow of the whole calibration type 10 is managed are described at [this page](./amo-encoder-joint-calibration-10-details.md)
```suggestion
Further details of how the workflow of the whole calibration type 10 is managed are outlined on [this page](./amo-encoder-joint-calibration-10-details.md).
```

2024-06-20 16:15 UTC, pattacini commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +It basically consists in moving the slow shaft towards one of the hardware limit, which is the position set in the calibration parameter `calibrationZero` in the configuration files, with a value of
```suggestion
The procedure basically consists in moving the slow shaft towards one of the hardware limits as defined in the position set within the calibration parameter `calibrationZero`. The value of the PWM used is in turn defined through the parameter `calibration1`. The joint moves until the limit is reached within a time window and within a predefined maximum length, whose values are coded in the firmware.
```

2024-06-20 16:15 UTC, pattacini commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +Finally, if the `hard-stop` limit position is found before the `CALIBRATION TIMEOUT` expires the zero of the `AMO encoder` is updated with the found offset and the whole calibration completes correct
```suggestion
Finally, if the `hard-stop` limit position is found before the `CALIBRATION TIMEOUT` expires, the zero of the `AMO encoder` is updated with the found offset and the whole calibration completes correctly; otherwise, the joint is moved to the `NOT CONFIGURED` state, the PWM is set to `zero` and the motor switched to `IDLE`.
```

2024-06-20 16:15 UTC, pattacini commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +The fw checks if the joint has reached the hard position by checking that the encoder position does not change for 1 second, that means the relative increase of joint position is smaller than 6.5 deg
```suggestion
The FW verifies if the joint has reached the hard position by checking that the encoder position does not change for 1 second, meaning that the relative increase of joint position is smaller than 6.5 deg (1200 iCubDegrees) within 1 second. The encoder position considered for the check is processed to filter out the spikes.
```

2024-06-21 08:28 UTC, MSECode commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +As already detailed in the [`calibration-10-procedure`](https://icub-tech-iit.github.io/documentation/robot_calibration_types/standard_calibration_types/#calibration-10) joints provided with the `AMO
Ok, I updated it.

2024-06-21 08:35 UTC, MSECode commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +As you can see in the above reported state machine, after the calibration command is received by the EMS, it arms a timer of 30 seconds, then it waits for the motor encoder calibration ending and the
Updated and squashed commits

2024-06-21 08:36 UTC, MSECode commented on docs/robot_calibration_types/standard_calibration_types.md
> +Further details to how the workflow of the whole calibration type 10 is managed are described at [this page](./amo-encoder-joint-calibration-10-details.md)
Updated and squashed commits

2024-06-21 08:36 UTC, MSECode commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +It basically consists in moving the slow shaft towards one of the hardware limit, which is the position set in the calibration parameter `calibrationZero` in the configuration files, with a value of
Updated and squashed commits

2024-06-21 08:36 UTC, MSECode commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +Finally, if the `hard-stop` limit position is found before the `CALIBRATION TIMEOUT` expires the zero of the `AMO encoder` is updated with the found offset and the whole calibration completes correct
Updated and squashed commits

2024-06-21 08:36 UTC, MSECode commented on docs/robot_calibration_types/amo-encoder-joint-calibration-10-details.md
> +The fw checks if the joint has reached the hard position by checking that the encoder position does not change for 1 second, that means the relative increase of joint position is smaller than 6.5 deg
Updated and squashed commits

2024-06-21 08:44 UTC, pattacini commented on docs/robot_calibration_types/amo_encoder_joint_calibration_10_details.md
> +This page shows how the calibration procedure used for `iCub 3/ergoCub` joints that mount an AMO encoder at the joint works.
```suggestion
This section illustrates the details of the calibration procedure used for the `iCub 3/ergoCub` joints that mount an AMO encoder at the slow shaft.
```

2024-06-21 08:44 UTC, pattacini commented on docs/robot_calibration_types/amo_encoder_joint_calibration_10_details.md
> +As you can see in the above-reported state machine, after the calibration command is received by the EMS, a timer of 30 seconds gets triggered; afterward, we want untile the motor encoder calibration
```suggestion
As you can see in the above-reported state machine, after the calibration command is received by the EMS, a timer of 30 seconds gets triggered; afterward, we wait until the motor encoder calibration ends; finally, the calibration procedure 10 commences.
```

2024-06-21 08:46 UTC, merged

2024-06-21 08:47 UTC, MSECode commented
> amendments

Thanks