added 22.04 page and ansible playbook guide
icub-tech-iit/documentation pull request #381
Opened 2024-12-17 15:38 UTC by davidelasagna

check https://github.com/icub-tech-iit/tickets/issues/2292#issuecomment-2548568290

2024-12-17 15:58 UTC, pattacini requested changes
Hi @davidelasagna 

Apparently, you forgot to commit/push some relevant files to your fork.

2024-12-17 16:19 UTC, traversaro commented on mkdocs.yml
>              - Installation from pre-built image: icub_operating_systems/icubos/installation-from-image.md
If the installation with pre-build image is outdated, I would not present it as first option in the list.

2024-12-18 08:36 UTC, davidelasagna commented on mkdocs.yml
>              - Installation from pre-built image: icub_operating_systems/icubos/installation-from-image.md
True, for sure we can swap orders and write a warning on top of the page saying that the pre-build is outdated

2024-12-18 08:55 UTC, traversaro commented on docs/icub_operating_systems/icubos/installation-from-scratch-22.04.md
> +    The installation procedure will overwrite the disk of your icub-head, so all data will be deleted.
Something that it is not clear to me: how do you attach the usb to the `ergocub-torso`/`icub-head` and you install without keyboard or mouse?

2024-12-18 09:21 UTC, traversaro commented
We can also do this in a follow up PR, but I think we also need to change the docs in https://icub-tech-iit.github.io/documentation/icub_operating_systems/icubos/icubos/ .

2025-01-02 09:21 UTC, pattacini commented
Let me merge the PR straight away to speed up things.
I'll then apply some amendments myself, whereas other mods can be suggested via successive PRs.

2025-01-02 09:22 UTC, pattacini approved these changes

2025-01-02 09:22 UTC, merged

2025-01-02 10:17 UTC, pattacini commented on mkdocs.yml
>              - Installation from pre-built image: icub_operating_systems/icubos/installation-from-image.md
See #382.

2025-01-02 10:24 UTC, pattacini commented
> Let me merge the PR straight away to speed up things. I'll then apply some amendments myself, whereas other mods can be suggested via successive PRs.

See:
- #382