added doc for iCub3 joints, Kinematics, robot calibration
icub-tech-iit/documentation pull request #81
Opened 2021-01-31 11:22 UTC by davidetome

📝  As per title this PR adds/updates the following docs  :

* [x] http://wiki.icub.org/wiki/ICub_joints
* [x] http://wiki.icub.org/wiki/ICub_joints_limits
* [x] http://wiki.icub.org/wiki/ICub_Model_naming_conventions
* [x] http://wiki.icub.org/wiki/ICubForwardKinematics
* [x] http://wiki.icub.org/wiki/Vergence,_Version_and_Disparity (related to https://github.com/icub-tech-iit/tickets/issues/386)
* [x] https://redmine.robotology.eu/projects/icub_hw/wiki/ICub3_joints_specifications

It also moves the  `ft-sensors` doc to the upper level.

✅ Once discussed, approved and merged I'll update the old wiki pages with a pointer to the new doc.

cc @pattacini @traversaro @maggia80

2021-01-31 12:46 UTC, pattacini requested changes
Very nicely done @davidetome 👍🏻 

As first feedback, we agreed on getting shot of the PPT files as they've been already ported in MD.

2021-02-01 08:18 UTC, davidetome commented
> Very nicely done @davidetome 👍🏻
> 
> As first feedback, we agreed on getting shot of the PPT files as they've been already ported in MD.

❌  `pptx` files removed in the last commit

2021-02-01 08:38 UTC, pattacini approved these changes

2021-02-01 08:39 UTC, pattacini commented
Thanks @davidetome!
Let's keep this PR open for a couple of days while I'll be reviewing it.

2021-02-01 13:00 UTC, pattacini requested changes
I would move the following topics under HW:
- F/T Sensors
- iCub Kinematics
- iCub 3

Further, I would

2021-02-02 14:44 UTC, davidetome commented
> I would move the following topics under HW:
> 
> * F/T Sensors
> * iCub Kinematics
> * iCub 3

done in the last commit 👍🏻

2021-02-02 14:51 UTC, pattacini commented on mkdocs.yml
> +        - ICubForwardKinematics Inertial:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-inertial.md
```suggestion
        - iCub FW Kinematics: icub_kinematics/icub-forward-kinematics/icub-forward-kinematics.md 
        - iCub FW Kinematics Arms:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-arms.md 
        - iCub FW Kinematics Fingers:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-fingers.md 
        - iCub FW Kinematics Head:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-head.md 
        - iCub FW Kinematics Legs:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-legs.md 
        - iCub FW Kinematics Inertial:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-inertial.md 
```

2021-02-02 14:53 UTC, pattacini approved these changes

2021-02-02 14:56 UTC, pattacini commented
Very nicely done @davidetome 🚀 
I would ask @traversaro to give a second look before I'll squash and merge the PR.

2021-02-03 22:08 UTC, merged

2021-02-03 22:08 UTC, pattacini commented
Merging, we can always amend the documentation later on.

2021-02-03 22:13 UTC, traversaro commented
Thanks, I actually started the review with some notes but it remained in the pending state! I will open separate issues for the improvements, but it is quite nice already!

2021-02-05 10:13 UTC, davidetome commented
Updated old pages with a pointer to the new doc